### ISSUE TITLE
Bug in error handling

### ISSUE THREAD

**Issue by dobragab** [ndevilla/iniparser#73]
I recently found a bug in error handling of `iniparser_load`. Look at [Line 732](https://github.com/ndevilla/iniparser/blob/master/src/iniparser.c#L732) of `iniparser.c`! That `break` jumps out of the `switch`, not the `while` loop processing the lines. `errs` is set, but processing will go on, `errs` will be overwritten if a following line is syntactically correct, so the returned dictionary won't be `NULL`. 

Currently there is no way that the programmer could detect the syntax error, only the user can (`stderr`). Look at Commit 8ffcea6f516270f84ef7716c983fd2982ecd9b91 pointing that out. 

I didn't create a pull request for this as I don't know what error handling strategies would I follow.

1. Stop at first syntax error, free everything and return `NULL`. 
2. Detect and print all syntax errors, free everything and return `NULL`. 
3. Print syntax error, but return a valid dictionary.

The current implementation varies between 2 and 3. If there was a valid Section or Value line after syntax error, it's 3, otherwise 2.

I provided a fix resulting in 1 (e78613270c28891215b2fa2a0b21914e9ee78175), but that's just ugly. Bad thing is, the `break`s are chaotic in `iniparser_load`. I can rewrite it using `goto` instead of random breaks, either implementing strategy 1 or 2, [like this](http://stackoverflow.com/questions/788903/valid-use-of-goto-for-error-management-in-c), if necessary.

It is your job to decide the strategy, feel free to cherry-pick these commits if you want strategy 1.

___

There is another huge problem in `iniparser_load` about error handling: it writes the message to `stderr`. This is just fine for CLI programs written in C, but consider the following:
* GUI applications that have `stderr` omitted, and would like show the message to the user.
* C++ wrapper for iniparser. In C++ it is usually better to throw something derived from `std::runtime_error` **containing** the message instead of arbitarily printing to `stdout`. 

So most C libraries have `const char * getlasterror()` to handle the problem, and this gives a workaround for both problems. You can see my approach: 83c45bf29452b1fdbe4181d2ae9dbb7605b2b7df

Note that this isn't perfect either. For example it contains possibility of buffer overflows, that could be solved by `snprintf`. Bad news: `snprintf` is not part of the C89 standard, and only the latest MSVC compilers have the C99 compatible version... 

This change has only a small impact on the API, so it can be changed without breaking  code based on iniparser. More bad news: CLI programs might expect that iniparser writes the errors to `stderr`. 

A possible solution: logging both into `stderr` and `ERRORBUFFER` by default, and adding `void iniparser_stderr(int enabled)` function that would toggle printing to `stderr`.

This is another question that You should decide. 

dobragab

**Comment by touilleMan** [comment]
Hi and sorry for the slow answer ;-)

For the first point, I've created PR #77, tell me if you see any caveat...

I agree with you about iniparser's stderr dumping of messages. To fix this, I've created a PR #76
which define a `iniparser_set_error_callback` function to allows user to define it custom callback receiving error messages.

**Comment by dobragab** [comment]
Hi,

I've checked PR #77. It prevents this piece of code to be reached:
```C
if (errs<0) {
    fprintf(stderr, "iniparser: memory allocation failure\n");
    break;
}
```
This means two things: 
* `iniparser: memory allocation failure\n` will never be written to stderr
* The loop will continue even if we are out of memory, because this `break` won't be hit. 

___

I've also checked PR #76. It looks like you've found a flexible solution that can be used pretty well. I don't think this is the case.

* First, I don't exactly know how many C programmers know how to write a variadic function, but I bet not everyone.
* Second, this doesn't give us the chance to keep the error message in memory, Simply because the length of the output is not limited, we can't get it before the callback is called, and the callback doesn't even get it. So we must redirect it to an endless stream, and still can't display it on a UI. If we are using it in C++, it still sounds impossible to print to a `std::string`, despite it is "endless".
* Third, the callback is called _before_ `iniparser_load` returns `NULL`. So if we set a callback that prints to a file, we still can't log the following:

```
We got the following error from iniparser:
iniparser: syntax error in config.ini (2):
a b
```

I've created PR #78 which fixes all these problems. However, the ini parsing will now stop at the first error.

**Comment by touilleMan** [comment]
> I've checked PR #77. It prevents this piece of code to be reached:

Thanks a lot for the catch, I've updated the PR :+1: 

> First, I don't exactly know how many C programmers know how to write a variadic function, but I bet not everyone.

I agree, this add some complexity. I see to solutions to lower this:
- Add a snippet of code in `iniparser_set_error_callback` documentation showing a template of error callback implementation
- Use `sprintf` beforehand to provide the error callback with a regular string. However this ask the question of the ownership of this string (should we return a malloced string that the callee is responsible to destroy ? or should we always use the same static buffer so the callee has to copy it if he wants to keep it ?)

>Second, this doesn't give us the chance to keep the error message in memory, Simply because the length of the output is not limited, we can't get it before the callback is called, and the callback doesn't even get it. So we must redirect it to an endless stream, and still can't display it on a UI. If we are using it in C++, it still sounds impossible to print to a std::string, despite it is "endless".

I guess we can solve this by providing a `INIPARSER_ERROR_MAXSIZE` like in PR #78 value which would guarantee the max length of the passed data.

> Third, the callback is called before iniparser_load returns NULL. So if we set a callback that prints to a file, we still can't log the following:

I'm not sure about this one: `iniparser_set_error_callback` can be called at any time (it just changes a static function pointer), so you should be able to call it first, then do your `iniparser_load` ?

@ndevilla Do you have time for this ? Changing the way errors are handled is not a light change so your point of view is mandatory.

- solution 1: replace `fprintf` by a user-configured callback (which would be by default `fprintf` of course)
- solution 2: provides an `iniparser_getlasterror` function to retrieve last error

My current concerns for solutions 2 is:
- API breakage: solution 1 by default act just like before. For solution 2 we can decide by default to print on stderr in addition to provide the `get_last_error` (behavior which could be disabled by `#define`) but this doesn't seems really elegant to me
- Memory eaten by the `ERRORBUFFER` which store the last error message. This can be costly on small systems (I you have more than 1Go of RAM, why bother doing C anyway :trollface: ), so we should think of the possibility to disable it. However this is more an interrogation than a strong concern for me so far.

**Comment by ndevilla** [comment]
Hi guys,
Sorry for chiming in late.

Rule #1: Do not break existing code. Adding stuff to the API is completely Ok, but modifying the default behaviour is not. Let us say this is as a courtesy to the many people who have been using the library for the past 20 years or so.

I completely agree that not everybody wants to have their errors tossed into stderr. Bit of context: when I first wrote this library I had to make the difficult choice of which error handling to provide. I quickly realized that no matter what I wrote, I could not satisfy everyone. Errors can be syslogged, dumped to a log file, printed on to stderr, returned in memory, qualified by an enum before returning, or just displayed on screen. FWIW, iniparser is used in many severely memory-restricted environments, but also in Windows games (Electronic Arts), Unix daemons (samba), interactive GUI-based or command-line programs, you name it. Since it is used in so many different contexts, no size can possibly fit all. I chose to provide the simplest possible error handling, hoping that people would adapt it to their own needs. The default error handling is a stupid fprintf. It has no API of any sort. You are expected to search and replace fprintf by your own code as you see fit. Of course that is not perfect either. Once you have started writing your own code into the library, you have to patch it back for further corrections, which is a royal pain.

The solutions you describe seem quite elegant and a better approach than I initially wrote. If I try to summarize, we would:

Switch from straight fprintf to a more generic ini_error() (variadic) function that could still default to printing to stderr. Previous users won't see any change.

Provide a new function that allows switching ini_error() to something user-provided. This way everyone should be able to plug-in their own error reporting without touching iniparser, as long as their error function replacement fulfils the same prototype. To be fair you do not even need a function for this, just make ini_error() assignable and assign your own function to it. Whatever.

We should avoid at all costs providing ourselves something that keeps errors in memory. Same thinking as above: no matter what we provide, we cannot cover all cases. Just focus on giving the opportunity for somebody to plug their own error system.

About returning as soon as you found one error: if you provide your own error function that is really your choice. But let me tell that: when I get a config file wrong, I like to know every place where I messed up in a single go. If you choke on the first encountered problem, you force your user to iterate for each blunder in the file. If your program takes 5 minutes to start up, iterations can become costly.  I guess this is a matter of personal preference, but again: users of this library are used to this behaviour, try not changing the default.

Hope that makes sense. Feedback welcome!

Nicolas

**Comment by touilleMan** [comment]
PR #76  and #77 has been merged to solve this
