### ISSUE TITLE
Compile the project on STM32 microcontroller with IAR

### ISSUE THREAD

**Issue by cedricgrimault** [ndevilla/iniparser#85]
Hello

I want to use this library on STM32 microcontroller compiler with IAR.
Has anyone ever performed this operation?

I already encounter problems. especially : 
- #include <unistd.h>  I do not call posix on stm32.
- ssize_t This type does not correspond to anything.

Thanks for your help

**Comment by touilleMan** [comment]
Iniparser has been compiled on a very large range of device (fun fact: it is embedded inside the smart fortwo for instance :smiley: ) so your usecase should no be too much of a burden.

I guess if your IAR compiler doesn't define `unistd.h` it is because you compile on windows, in such case you can create your own `unistd.h` containing windows equivalents like `io.h` (see http://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c)
